/**
 * Service content data extracted from blade templates.
 * Used by city pages ([slug]) and market-we-serve pages.
 * {cityName} placeholders are replaced at render time.
 */

const SERVICE_CARDS = {
  'Social Media': [
    { title: 'Social Media Marketing Agency {cityName}', desc: 'A social media marketing agency {cityName} is always a reliable support system for all types of businesses. Whether you own a small store or a large mall, social media marketing campaigns target your business-based audience using different platforms like Facebook, LinkedIn, Instagram, Twitter, etc. The expertise of Digital Solution 360 makes everything possible using the proper strategy, content creation, advertising, brand awareness, and ROI for {cityName}-based companies.' },
    { title: 'Social Media Marketing Company {cityName}', desc: 'Are you ready to elevate your online business? Here is Digital Solution 360, a dependable social media marketing company {cityName}. With us, you will get the best and specialized social media marketing. Elevate your business presence online without delay. With our expert guidance, we launch data-driven campaigns and excellent creative strategies. This initiates the growth in improving customer interaction, driving leads across various social media platforms.' },
    { title: 'Social Media Marketing Agency in {cityName}', desc: 'A trustworthy social media service provider offers comprehensive digital solutions for businesses seeking to expand their social presence. With Digital Solution 360, the social media services are getting more intense and productive. As a responsible social media marketing agency in {cityName}, our experts provide tailored content, run performance-driven ads, and generate incredible results. It is time to build credibility. Join Digital Solution 360 for improved social media performance.' },
    { title: 'Social Media Agency {cityName}', desc: 'Improving digital signatures on social media is not a difficult task anymore. When you join Digital Solution 360, you understand the impact of evolving with the best. Social media campaigns are necessary for every group of businesses. With the best social media agency {cityName}, our experts launch the finest categories suited to every business. Every time you want more growth and foster your online royalty, hire us to do the job for you effortlessly at a minimal price.' },
    { title: 'Digital Marketing Companies {cityName}', desc: 'An expert in digital marketing or social media is hard to find under certain budgets and processes. However, when you pick your right social media work partner, you unlock the potential of premium services, including on-time assistance and online elevation of your business. Let\'s build an improved business image over the internet. Are you looking for a wide range of services among the best digital marketing companies {cityName}? Join Digital Solution 360 today!' },
    { title: 'Social Media Agency in {cityName}', desc: 'Businesses that need customized solutions from a dependable social media agency in {cityName} can easily achieve this. With Digital Solution 360\'s brilliant strategies, we unlock the best range of social media services fitting your business\' needs. In the entire services, our talented experts provide target-driven content, paid promotions, campaigns, and other services appropriate for different social media platforms. Let\'s take your business towards growth and sustainability in the online world with us today!' },
    { title: 'Best Social Media Agency in {cityName}', desc: 'Are you demanding data-driven online marketing across various social media platforms? Well, you need someone who has both the experience and the expertise to pull this off. With Digital Solution 360, our services make us the best social media agency in {cityName}. Thanks to our experts in social media who know how to let a business thrive under different circumstances. We let your business grow and go beyond your competitors in {cityName}. Join us today!' },
    { title: 'Social Media Marketing {cityName}', desc: 'In every world of business, the term "marketing" holds an impact. It holds the same result in the social world as well. With Digital Solution 360, businesses can thrive and grow to new heights successfully with the help of an elite team of social media marketers. We manage to do every possible work so that your business can gain the best results without affecting its reputation and performance over time. The creative approach from our team has always performed. Are you waiting for a reliable team of social media marketing {cityName}? Join Digital Solution 360 to build a positive online reputation for brands in {cityName}.' },
    { title: 'Best Social Media Marketing Agency in {cityName}', desc: 'Boosting a business over social media platforms requires discipline, continuous efforts, plans, and execution. Do you own a small business in {cityName} and want more growth in the online world to expand your reach? Yes, Digital Solution 360 is the right solution for you. With our tailored campaigns and data-driven insights, we prepare the best plans for elevating your online growth. Let\'s chase your business goals while catering to {cityName}\'s diverse customer base with the best social media marketing agency in {cityName}.' },
    { title: 'Social Media Company in {cityName}', desc: 'A dependable social media agency always delivers up to the mark services without causing any delay. It is time for every business to grow more with the best social media company in {cityName}. Businesses that love to gain more audience in the online world, social media platforms are the best options. To lead from the front and better than your competitors, hire a reliable company in {cityName} called Digital Solution 360. The tailored solution we provide is always giving the best results for the clients across various business types and sizes. Why do you wait there? Join the revolution today!' },
    { title: 'Social Media Digital Agency in {cityName}', desc: 'A genuine social media marketing agency keen to specialize its services while creating, managing, and optimizing every required detail about your brand\'s online presence. In this way, Digital Solution 360 can boost sales and drive engagement for the businesses. Hiring a social media digital agency allows businesses to leverage expert knowledge and stay updated with the latest trends and platform algorithms. Experts consistently provide valuable insights and data-driven strategies to enhance ROI. It\'s time to connect with us digitally and avail all the required benefits with ease. Let\'s create meaningful connections with audiences on a larger scale. Join Digital Solution 360 today.' },
    { title: 'Best Way to Advertise on Social Media in {cityName}', desc: 'Wait no more to publish your services on the online market in any region! With the experts in business from the Digital Solution 360, we craft high-quality and visually appealing content paired with strong call-to-actions. These types of ads and social media campaigns are allowing your business to capture attention and drive conversions. We are strongly determined and consistent in monitoring and optimizing ad campaigns based on real-time analytics. Well, this is key to maximizing advertising budget effectiveness. Wait no more and join the elegance of our advertisement on social media.' },
    { title: 'Building Your Brand on Social Media in {cityName}', desc: 'The real challenge for any social media agency is to provide long-term stability and growth for its clients over its competitors. That\'s why you need someone who is trusted and experienced. Understanding your customer demographics and behavior on each platform helps in choosing the most impactful social media channels for your small business. We work on platforms like Instagram, Pinterest, Twitter, LinkedIn, and other options to boost your B2B reach among small businesses and customers. Let\'s not demoralize due to lack of poor brand performance. With Digital Solution 360, building your brand on social media is much easier and budget-friendly. Bring the best online version of your business with us.' },
    { title: 'Best Social Media for Small Business in {cityName}', desc: 'For small businesses, it is hard to collaborate with different influencers, but we customize everything that fits strongly with the structure of the business. The best social media marketing companies handle the entire management of your small brand\'s social accounts, freeing up your internal resources for other tasks. At Digital Solution 360, the customized outsourcing for your business adds productive benefits from scalable services, adjusting efforts based on campaign needs and budget constraints. For small businesses, we reach comments, messages, and interactive features like polls that build a community around your brand. Bring the best version of your brand today!' },
    { title: 'Social Media Outsourcing Companies in {cityName}', desc: 'Are you looking for beneficial and budget-friendly social media outsourcing companies? At Digital Solution 360, we provide expertise in content creation, schedule management, community engagement, and social listening to keep your brand relevant. We are glad that our social media team can handle the entire management of your brand\'s social accounts and give you the boost that you need the most. We are here to free you from the burden and let you focus on other tasks. Partnering with a reliable social media outsourcing company like Digital Solution 360 ensures consistent brand messaging and professional handling of customer interactions online.' },
  ],

  'Digital Marketing': [
    { title: 'Digital Marketing Company in {cityName}', desc: 'Digital Solution 360, the top digital marketing company in {cityName}, offers comprehensive services including SEO, PPC, social media marketing, and eCommerce solutions to drive your business\'s online success.' },
    { title: 'Digital Marketing Service Near Me', desc: 'Looking for top-notch digital marketing services near you? Digital Solution 360 offers expert SEO, social media marketing, PPC, and more to boost your online presence and drive results. Partner with us for tailored strategies and outstanding performance.' },
    { title: 'SEO Company in {cityName}', desc: 'As the top SEO company in {cityName}, Digital Solution 360 provides professional optimization services to raise search engine ranks, increase organic traffic, and improve your website\'s visibility.' },
    { title: 'Best Digital Marketing Service in {cityName}', desc: 'Digital Solution 360 offers the best digital marketing services in {cityName}, including social media marketing, SEO, PPC, bulk email and SMS marketing, and eCommerce solutions.' },
    { title: 'Best Local SEO Services Near Me', desc: 'We specialize in local SEO to help small and local businesses win "near me" searches and relevant local intent queries.' },
    { title: 'Best Email Marketing Services in {cityName}', desc: 'Engaging campaigns, list management, and performance optimization to increase engagement and conversions.' },
    { title: 'Best Mobile App Marketing Services', desc: 'Targeted ads, user engagement, ASO, and analytics for installs and retention.' },
    { title: 'Best Content Marketing Services', desc: 'High-quality, brand-safe, audience-aware content to power growth.' },
    { title: 'Digital Competitive Analysis in {cityName}', desc: 'We analyze competitors to craft winning strategies and strengthen visibility.' },
    { title: 'Social Media Marketing Service', desc: 'Content, management, and brand building on Facebook, Instagram, LinkedIn, and more.' },
    { title: 'Google Local Services Advertising Near Me', desc: 'Tailored local ads to generate quality leads and new customers.' },
    { title: 'Digital Marketing Company Near Me', desc: 'Expert SEO, SMM, PPC and more. Elevate your online presence with us today!' },
    { title: 'Digital Marketing Agency Near Me', desc: 'Professional SEO, social, PPC and more — get in touch now.' },
    { title: 'Digital Promotion Agency in {cityName}', desc: 'Leading promotion services including SEO, SMM, and PPC.' },
    { title: 'Digital Marketing Prices in {cityName}', desc: 'Typical retainer ranges ₹10,000–₹50,000+/mo depending on scope and complexity.' },
  ],

  'Web Development': [
    { title: 'Affordable Web Design & Development Company in {cityName}', desc: 'Digital Solution 360 is an affordable web design & development company in {cityName}. Book today for an appointment.' },
    { title: 'E-commerce Web Development in {cityName}', desc: 'Launch your online store with the best e-commerce web development in {cityName}. Digital Solution 360 helps you to fly in the digital world. Call for an appointment.' },
    { title: 'Web Developer Agency Near Me', desc: 'Need for website development in your area don\'t be sad, just find on Google best Web developer agency near me and call Digital Solution 360 for consultation.' },
    { title: 'Hire Web Developer in {cityName}', desc: 'Hire web developer in {cityName}, and Digital Solution 360 has the best web developer for web development services. We have a team of skilled and experienced developers.' },
    { title: 'Responsive Website Design', desc: 'We prefer custom solutions. We develop websites with the first mobile responsive designs for responsive-friendly designs. Digital Solution 360 is the best responsive website design in {cityName}.' },
    { title: 'Custom Web Development Services in {cityName}', desc: 'Digital Solution 360 offers fully customized solutions to the clients. We offer custom theme integration, mobile responsiveness designs, and many more according to the business needs. Call today for the meeting.' },
    { title: 'Website Development Company in {cityName}', desc: 'Digital Solution 360 is a well-known website development company in {cityName}. Our experienced and skilled team specializes in custom website design, WordPress solutions, UI/UX design, and web page development.' },
    { title: 'Website Designing & Development Company in {cityName}', desc: 'Choose Digital Solution 360 for a website designing & development company in {cityName}. We offer customized designs, seamless navigation, and user-friendly interfaces with the latest technology.' },
    { title: 'Website Designing & Development Services', desc: 'With Digital Solution 360, you get high-quality, scalable, and feature-rich websites that set you apart. Our best website designing and development services enhance your online visibility.' },
    { title: 'Website Designing Company in {cityName}', desc: 'If you want to make your website unique, responsive, and user-friendly then you are at the right place for a website designing company in {cityName}.' },
    { title: 'Web Development Companies Near Me', desc: 'When you search for web development companies near me, Digital Solution 360 is only the best digital marketing service that provides top-notch web development services.' },
    { title: 'Website Design & Development', desc: 'Choose Digital Solution 360 for the best website design & development services. You will get better design, functionality, and user engagement.' },
    { title: 'Website Developer in {cityName}', desc: 'Your trusted website developer in {cityName} — Digital Solution 360, specializes in custom web solutions, creating responsive websites, and web page development. Our expertise in high-performance SEO-friendly designs.' },
    { title: 'Web Application Development', desc: 'In the digital world today, it\'s very crucial for businesses to stay competitive. Step ahead with a well-designed web application to improve efficiency and online visibility. At Digital Solution 360, we offer end-to-end web application development services including E-commerce development, UI/UX design, API development, and integration.' },
    { title: 'Website Development Near Me', desc: 'Digital Solution 360 is your go-to partner for website development near me, delivering expert solutions for all types of businesses. Grow your business with our expert website development services and stay always ahead in the digital markets.' },
    { title: 'Website Management Services', desc: 'The team of Digital Solution 360 is always there to ensure your website runs smoothly and efficiently. Partner with us for trustworthy website management services. Our services include regular updates, security monitoring, performance optimization, etc.' },
    { title: 'Website Development Services', desc: 'Investing in professional website development services is very crucial for business growth in the digital world. Contact Digital Solution 360 for the best web development services.' },
    { title: 'Website Developers Near Me', desc: 'When you search for website developers near me you can easily find Digital Solution 360, a solution for all problems. Our experienced and expert developers provide services like custom website design, e-commerce solutions, CMS development, etc.' },
    { title: 'Website Company in {cityName}', desc: 'Contact Digital Solution 360 for the best website company in {cityName}. Our skilled development team delivers the best services and enhances your business growth.' },
    { title: 'Web Development Services', desc: 'Digital Solution 360 offers various web development services that enhance your digital presence. We offer services like custom website design, e-commerce development, CMS solutions, etc.' },
    { title: 'Website Development Costs', desc: 'Digital Solution 360 always offers very affordable digital marketing services for everyone. Our website development costs vary based on factors such as design, features, and customization. Our experts ensure high-quality design, functionality, and user experience at very genuine costs.' },
    { title: 'Website Design Services', desc: 'To help your business and establish your website in a digital platform. Digital Solution 360 offers great website design services at very affordable prices. Choose our top-notch website design services today.' },
    { title: 'Web Development Company', desc: 'Digital Solution 360 is no doubt the top web development company in the online world. We deliver specialization in web development, custom web design, and various web solutions with expertise in WordPress. Digital Solution 360 provides skilled website developers for all website development problems.' },
  ],

  'Google Business': [
    { title: 'Google My Business Company in {cityName}', desc: 'Digital Solution 360 offers excellent Google My Business management in {cityName}. Our specialty lies in enhancing local visibility, bringing in more business, and improving your online reputation through GMB profile optimization. They make sure your company stands out in local search results with their in-depth understanding and customized tactics.' },
    { title: 'Google My Business Services in {cityName}', desc: 'The Google My Business services offered by Digital Solution 360 in {cityName} might help you improve your local presence. We include review management, profile setup, optimization, and frequent updates to increase your exposure in local searches. Have faith in our experienced employees to successfully grow your consumer base and improve your online presence.' },
    { title: 'Best Google My Business Agency in {cityName}', desc: 'Find the top-rated Digital Solution 360 Google My Business agency in {cityName}. Known for their skillful GMB management, they monitor reviews, maximize the impact of profiles, and improve local visibility.' },
    { title: 'Google My Business Near Me', desc: 'Google My Business optimization services in {cityName}, call now at +918651092179 for "local business near me".' },
    { title: 'Google My Business Expert', desc: 'If you want to handle all search engine optimization and marketing tasks, you should hire an SEO/SMM expert. Therefore, we are offering all associated services at the Best Price.' },
    { title: 'Google My Business Expert in {cityName}', desc: 'Digital Solution 360 Google My Business expert SEO/SMM in {cityName} | Google My Business | SMM experts | Facebook marketing | call- +918651092179.' },
    { title: 'Google My Business Specialist in {cityName}', desc: 'Digital Solution 360 is the best-experienced expert in SEO in Google My Business specialist {cityName} which can help you with Google My Business.' },
    { title: 'My Business Listing', desc: 'Increase your local presence by using the Google My Business listing services offered by Digital Solution 360. To increase visibility and draw clients, we take care of profile setup, optimization, review management, and frequent updates. Put your trust in our knowledge to produce an engaging GMB listing that improves online reputation and encourages interaction.' },
    { title: 'Google My Business Management in {cityName}', desc: 'Digital Solution 360 Google My Business Service, the Best Google My Business Agency in {cityName} to manage SMM. We are a Google Partner SEO agency in India.' },
    { title: 'Best SMM Management', desc: 'Digital Solution 360 offers superior Social Media Management (SMM). We provide a wide range of services, such as engagement with audiences, ad campaign management, performance analytics, and content production. Our team of professionals makes sure your business is noticeable on social media sites like Facebook, Instagram, Twitter, and LinkedIn, increasing interaction and optimizing your online visibility.' },
    { title: 'GMB Management Services', desc: 'Make an appointment with Digital Solution 360\'s top specialists to handle GMB in {cityName}, and take advantage of exclusive offers and discounts at the time of booking.' },
  ],

  'Wordpress Development': [
    { title: 'WordPress Development Company', desc: 'WordPress is one of the easiest and most powerful content management systems. Digital Solution 360 is the best WordPress development company providing services like custom WordPress theme development, plugin customization, WordPress speed optimization SEO, and integration with social media apps for your website.' },
    { title: 'WordPress Website Developer', desc: 'If you are looking for the best WordPress website developer in {cityName}, Digital Solution 360 has you covered. We provide customized, high-performance websites for all types of businesses. WordPress offers easy content management, thousands of plugins, and smooth integration.' },
    { title: 'WordPress Development Services', desc: 'Elevate your brand with Digital Solution 360 which offers WordPress development services to your business in {cityName}. You get a professional website that boosts your online presence and progress in the online marketplace.' },
    { title: 'WooCommerce Development Agency', desc: 'Digital Solution 360 creates high-performance online stores according to your business needs. Our experienced team provides end-to-end WooCommerce development services. Our expert developers cooperate 24/7 and provide a better user-friendly shopping experience. Partner with us to build a fully WooCommerce store that meets your brand\'s amazing requirements.' },
    { title: 'WordPress Development Agencies', desc: 'Digital Solution 360 is one of the top WordPress development agencies, providing expert solutions for your online business. We specialize in WordPress website customization, theme customization, plugin development, and optimization.' },
    { title: 'WordPress Web Development Agency', desc: 'Whether you need an eCommerce store, corporate websites, etc. choose our WordPress web development agency to build a professional, engaging, and completely functional website.' },
    { title: 'Custom WordPress Development Services', desc: 'Our goal is to provide seamless and functional websites for any business purpose. Digital Solution 360 specializes in custom WordPress development services. Choose the best and build the next brand.' },
    { title: 'WordPress Web Development Services', desc: 'Partner with Digital Solution 360 for professional and SEO-friendly websites. Digital Solution 360 offers experience and expertise in WordPress web development services. Today it is very necessary for any business looking to establish a strong platform in the digital world.' },
    { title: 'WordPress Website Developer Near Me', desc: 'If you are searching for a WordPress website developer near me surely, you will get the best WordPress website developer company Digital Solution 360, offering professional website custom designs and development services.' },
    { title: 'WordPress Website Development Agency', desc: 'Digital Solution 360 is the best WordPress website development agency, that offers custom website designs and development services whether you need an eCommerce website, corporate website, or anything our developers provide you modern approach to a website to enhance the brand and increase online growth.' },
    { title: 'Best WordPress Website Developers', desc: 'Digital Solution 360 provides the best WordPress website developers in {cityName}, delivering high-quality, custom-built websites for your businesses. Our expert developers offer experience and technical solutions to enhance online presence.' },
    { title: 'Top WooCommerce Development Companies', desc: 'Digital Solution 360 is a well-known WordPress website development company, that specializes in custom WooCommerce store development, plugin integration, theme customization, etc. Our expert developers provide the best services according to the target audience. Digital Solution 360 is a star among the top WooCommerce development companies.' },
    { title: 'Top WordPress Developers', desc: 'Elevate your business with Digital Solution 360 and grow your business with the top WordPress developers with us. We specialize in WordPress design and development and complete functional websites with a very seamless user experience.' },
    { title: 'Website Development on WordPress', desc: 'If you need a WordPress website that enhances your online presence. Choose the best WordPress website development on WordPress. Our skilled team designs responsive, SEO-optimized websites. We focus on customer satisfaction.' },
    { title: 'WordPress Website Designing Services', desc: 'Elevate your business with our professional WordPress website designing services and take your business to the next level. Digital Solution 360 offers the best WordPress website designing services. Our experts are well-known for WordPress website design services.' },
    { title: 'WordPress Website', desc: 'Digital Solution 360 is a top-notch company that offers WordPress websites from theme customization to plugin integration. Whether you need a business site, or eCommerce store, at Digital Solution 360, we turn ideas into amazing websites that increase engagement and conversions.' },
    { title: 'Best WordPress Website Maintenance Services Near Me', desc: 'Regular maintenance of a WordPress website is not just for once but it requires constant care and updating. If a failure in maintenance it may cause several problems such as security breaches, slow speed, links broken, and poor user experience. The best way to keep your WordPress website up-to-date and running consistently is by investing in Digital Solution 360, the best WordPress website maintenance services near me.' },
    { title: 'WordPress Development Company in {cityName}', desc: 'Digital Solution 360 is a leading WordPress development company in {cityName}, that offers various customization for websites. As a trusted WordPress development company, we leverage the latest tools and technologies.' },
    { title: 'WordPress Web Design Company Near Me', desc: 'Look out for the best WordPress web design company near me and your search will be finished at Digital Solution 360, an online platform that prioritizes your specific objectives. We develop websites with modern approaches and our professionals work efficiently with clients and assist 24/7.' },
  ],

  'Content Writing': [
    { title: 'Content Writer in {cityName}', desc: 'You should choose the best content writer from Digital Solution 360 in {cityName}.' },
    { title: 'Content Writer Near Me', desc: 'If you search on Google for a content writer near me you will find Digital Solution 360 the best choice for your website writing in {cityName}.' },
    { title: 'Content Writing Services', desc: 'Best content writing services are provided by Digital Solution 360 in {cityName}.' },
    { title: 'Content Writing Agency', desc: 'We are one of the leading content writing agencies in {cityName}. Call our experts to book now.' },
    { title: 'Professional Content Writer in {cityName}', desc: 'We have a team of professional content writers in {cityName}. Give your business unique content — talk to our experts.' },
    { title: 'Content Writing Agency in {cityName}', desc: 'Expert team delivering compelling, high-quality content — why we are the best content writing agency in {cityName}.' },
    { title: 'Content Writing Company in {cityName}', desc: 'Book our service today — the best content writing company in {cityName}.' },
  ],
};

const SERVICE_FAQS = {
  'Digital Marketing': [
    { q: 'Which is best digital marketing company in {cityName}?', a: 'Finding the best digital marketing company in {cityName}. You can definitely opt for Digitalsolution360. We are the best online marketing company for SEO Services, SMO Services, SMM Services, Youtube Marketing and all.' },
    { q: 'How much does a digital marketing package cost in {cityName}?', a: 'Usually there are a lot of companies with different price charts. You can go with us because we are best digital marketing company in {cityName}. Our services prices start with just 5,000 for SMO, minimum price for SEO will be 9,999/-' },
    { q: 'How can I get started with your digital marketing services in {cityName}?', a: 'Getting started with our digital marketing services is easy! Simply reach out to us through our contact page or schedule a consultation with our team. We\'ll discuss your requirements, provide a personalized proposal, and guide you through the process of achieving your digital marketing goals in {cityName}.' },
    { q: 'How do you determine the cost for SEO services in {cityName}?', a: 'The cost of our SEO services in {cityName} is determined based on factors such as keyword competitiveness, website size, current optimization status, and desired ranking goals. We offer transparent pricing with clear deliverables to ensure you get the best value for your investment. We can serve you SEO Services at just 9,999 INR.' },
    { q: 'Do you offer package deals for digital marketing services in {cityName}?', a: 'Yes, we do offer package deals for our digital marketing services to provide comprehensive solutions at competitive prices. These packages are designed to meet the diverse needs of businesses in {cityName} and can be customized based on your budget and objectives.' },
    { q: 'Would my business benefit from Digital Marketing Services?', a: 'Every single brand has to have an online representation of the business. However, your digital footprint won\'t have any impact if you don\'t market it successfully. Every business would benefit from an ongoing, comprehensive digital marketing strategy and the support of an expert marketing team.' },
  ],

  'Web Development': [
    { q: 'What services does your web development company provide?', a: 'We offer a wide range of web development services, including website design, development, e-commerce solutions, CMS development, custom web applications, and more.' },
    { q: 'How long does it take to build a website?', a: 'The timeline for website development depends on the complexity and requirements of the project. We work closely with our clients to determine realistic timelines and deliver high-quality websites within the agreed-upon timeframes.' },
    { q: 'Do you offer responsive design for mobile devices?', a: 'Yes, all our websites are designed and developed to be fully responsive, ensuring optimal viewing experiences on various devices, including mobile phones, tablets, and desktop computers.' },
    { q: 'Can you help with website maintenance and updates?', a: 'Absolutely! We provide ongoing website maintenance and support services to ensure your website remains secure, up-to-date, and performs optimally. From content updates to regular backups and security enhancements, we\'ve got you covered.' },
    { q: 'Are your websites optimized for search engines?', a: 'Yes, we prioritize search engine optimization (SEO) during the development process. Our websites are built with SEO best practices in mind, ensuring they are properly structured, have optimized content, and are easily discoverable by search engines.' },
  ],

  'Google Business': [
    { q: 'Is Google My Business a free service?', a: 'Google My Business is absolutely a free service, but creating an appearance over there is a technical task. There are many steps from getting profile verification on GMB to phone number add-on. All things can\'t be managed by self. You can consult the best GMB management company in India. We will help you in all steps and create your powerful presence over there.' },
    { q: 'What is Google my Business SEO?', a: 'Google My Business (GMB) SEO refers to the process of optimizing your Google My Business profile to improve its visibility in local search results. This optimization aims to enhance your business\'s online presence and attract more customers who are searching for products or services like yours in a specific geographic area.' },
    { q: 'How can I improve my GMB profile?', a: 'Improving your Google My Business (GMB) profile with the assistance of a GMB management service provider involves several key strategies. They start by ensuring your profile is fully optimized with accurate business information, high-quality photos, and a compelling business description. GMB management services implement local SEO techniques to enhance your profile\'s visibility in local searches, including keyword optimization and citation building.' },
    { q: 'How to get top listing on Google?', a: 'Achieving a top listing on Google involves strategic efforts with the assistance of a GMB management service provider company. They start by thoroughly optimizing your Google My Business (GMB) profile with accurate business information, high-quality visuals, and a compelling description. These companies implement local SEO strategies, including keyword optimization, citation building, and NAP consistency across online platforms.' },
    { q: 'How do I set up a Google My Business listing?', a: 'To set up a Google My Business listing in India, begin by signing in to your Google account and visiting the Google My Business website. Click on "Manage now," enter your business name, and choose the appropriate category. Fill in your business address, phone number, and website details. Verify your business either by postcard or via phone if eligible. Once verified, complete your profile with photos, business hours, and a description.' },
    { q: 'How do I manage reviews on Google My Business?', a: 'Managing reviews on Google My Business is crucial for maintaining a positive online reputation. Start by regularly monitoring incoming reviews through the Google My Business dashboard or mobile app. For each review, whether positive or negative, respond promptly and professionally. Thank customers for positive feedback and address any concerns or issues raised in negative reviews with empathy and a willingness to resolve problems.' },
    { q: 'What are the benefits of using a Google Listing Service?', a: 'Using a Google Listing Service offers several significant benefits for businesses. It enhances online visibility, provides a platform to showcase essential business information, allows businesses to engage directly with customers through posts, messages, and reviews, and is generally free, making it a cost-effective way to enhance your online presence.' },
    { q: 'What should I do if my Google My Business listing is suspended?', a: 'If your Google My Business listing is suspended, first understand the reason provided by Google. Common reasons include policy violations, inaccurate information, or suspected fraud. Review Google\'s guidelines, correct any violations, and submit an appeal through the Google My Business dashboard with necessary documentation.' },
    { q: 'Why is my Google My Business listing not appearing in search results?', a: 'Ensure that your listing is verified and accurately filled out with complete business information. Check that your business category and description are relevant and specific. Consider your location and whether you\'ve optimized your listing for local searches with appropriate keywords. If recently updated, it may take time for Google to index and display it.' },
  ],

  'Social Media': [
    { q: 'How soon can I see results from social media advertising?', a: 'Many businesses see engagement like clicks or inquiries within the first few weeks, but bigger results like sales growth usually take a few months of consistent effort and optimization.' },
    { q: 'Why is Facebook advertising management important for businesses?', a: 'Managing Facebook ads the right way ensures that your budget is spent wisely. With proper targeting, tracking, and optimization, businesses can reach the right audience, gain qualified leads, and see a better return on every penny invested.' },
    { q: 'Can small businesses hire Digital Solution 360?', a: 'Yes, small businesses can hire us and get all the advantages related to SMM campaigns.' },
    { q: 'Do you create content along with managing campaigns?', a: 'Yes, our team takes care of everything—from writing captions and designing creatives to producing ad copies and videos.' },
    { q: 'Which platforms are most effective for SMM marketing?', a: 'Facebook and Instagram work well for most consumer-focused brands, while LinkedIn is powerful for professional and B2B marketing. The right platform really depends on your audience and goals.' },
    { q: 'What services does a social media digital agency provide?', a: 'At Digital Solution 360, we are experts at providing the best brands\' online presence. We elevate your online reach across different social media platforms like Instagram, Facebook, Twitter, LinkedIn, etc. Our services include content creation, paid advertising campaigns, audience targeting, analytics tracking, and engagement strategies — all meant to boost brand awareness and customer interaction effectively.' },
    { q: 'What is the best way to advertise on social media for my business?', a: 'The best way to represent your business on social media is to get to know your targeted audience. Based on the niche of your business, our experts prepare engaging, visually appealing ads with clear calls-to-action. We combine retargeting, A/B testing and influencer collaborations to improve ad performance and increase ROI.' },
    { q: 'How can I build my brand on social media effectively?', a: 'Building your brand on social media requires proven methods and a sustainable team. At Digital Solution 360, we focus on consistent posting of valuable content, authentic engagement with your audience, and maintaining a clear brand voice across all channels. We use story-telling, influencer partnerships, and interactive features to create a loyal community and long-term customer relationships.' },
    { q: 'Which social media platform is best for small businesses?', a: 'Different businesses require different platforms. For a small business, it depends on the customer\'s demands. When you invest in Digital Solution 360, we prepare a customized solution that helps you reach younger audiences, provides trend-oriented customizations, optimal engagement and growth, and smooth social media management.' },
    { q: 'Why should I consider social media outsourcing companies?', a: 'At Digital Solution 360, we provide proven solutions on social media outsourcing specific to businesses and regions. Our experts handle content creation, scheduling, community engagement, and analytics, freeing your internal team from various stresses related to social media marketing.' },
  ],

  'Wordpress Development': [
    { q: 'Is WordPress good for web development?', a: 'Yes, it is the most widely used content management system worldwide. It\'s one of the most preferred choices among developers for building websites and online stores.' },
    { q: 'How long does it take to develop a WordPress website?', a: 'It depends on your specific requirements. If your development needs are limited, it takes less time. Digital Solution 360 has a track record of building websites as soon as possible.' },
    { q: 'Can you make my website mobile-friendly?', a: 'Yes, we do all possible things to make your website more attractive and user-friendly. We create websites so accessible that they are also mobile-friendly.' },
    { q: 'Why should I trust Digital Solution 360 for WordPress development?', a: 'We have a team of skilled and experienced WordPress designers and developers who are dedicated to creating unique and modern approach websites for business. Customer satisfaction is our top priority.' },
    { q: 'What is a WordPress development agency?', a: 'It is typically made up of project managers, designers, developers, and other roles that come together to design and develop projects for their clients using WordPress.' },
    { q: 'How much does a WordPress agency cost?', a: 'It depends from agency to agency but Digital Solution 360 provides very affordable services where you can get custom design service and custom development with unique features.' },
  ],

  'Content Writing': [
    { q: 'What are the types of content writing?', a: 'There are many types including blog writing, article writing (interviews, customer stories, press releases), ghost writing, technical writing, social media writing, email writing, and ad & promo writing.' },
    { q: 'What makes a good content writer?', a: 'Key skills include good written communication, proofreading and editing abilities, imagination, knowledge of target readers, SEO optimization tools familiarity, time management, research analysis, and storytelling.' },
    { q: 'How much do content writers charge in {cityName}?', a: 'A professional content writer in {cityName} charges between 60 paise to 4 Rs per word. It varies according to skill and expertise of the writers.' },
    { q: 'Can you write content for my website?', a: 'Yes, we have a team of professional content writers with expertise in writing varieties of website content and content creation techniques for A-to-Z type of writing according to your audience.' },
    { q: 'Is content writing a good career option?', a: 'Content writing is an evergreen career. Even in a world of AI, clients prefer professional human writers who understand the basics and targeted audience. It is a profitable career at individual and team levels.' },
  ],
};

export { SERVICE_CARDS, SERVICE_FAQS };
